# Generated by Django 3.1.7 on 2021-03-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='developer',
        ),
    ]
