# Generated by Django 3.1.6 on 2021-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('problem', models.TextField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
