# Generated by Django 3.1.6 on 2021-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem',
            field=models.CharField(max_length=300),
        ),
    ]
